services:
  order-app:
    image: orders:1.0
    ports:
      - 8084:8084
    depends_on: 
      - postgres 
    environment:
      DB_HOST: postgres
      USER: postgres
      PASS: Emilgibi@123
  postgres:
    image: postgres 
    environment:
      POSTGRES_PASSWORD: Emilgibi@123
      POSTGRES_USERNAME: postgres

  inventory-app:
    image: inventory:1.0
    ports:
      - 8082:8082
    depends_on: 
      - postgres 
    environment:
      DB_HOST: postgres
      USER: postgres
      PASS: Emilgibi@123
 

  products-app:
    image: products:1.0
    ports:
      - 8081:8081
    depends_on: 
      - postgres 
    environment:
      DB_HOST: postgres
      USER: postgres
      PASS: Emilgibi@123
  
  user-app:
    image: user:1.0
    ports:
      - 8083:8083
    depends_on: 
      - postgres
    environment:
      DB_HOST: postgres
      USER: postgres
      PASS: Emilgibi@123
      ORDER_SVC: order-app
      PRODUCT_SVC: products-app
      INVENTORY_SVC: inventory-app
    


